### ISSUE TITLE
"Aborted" message on Pipe example

### ISSUE THREAD

**Issue by forbisc** [saghul/pyuv#197]
Running the pipe example fails for me.  

$ python --version
Python 2.7.5
$ python3 --version
Python 3.3.2
$ cat abc.txt
abc
$ python test.py < abc.txt
Aborted
$ python3 test.py < abc.txt
Aborted

The issue was discussed here as well:
https://catalyst.uw.edu/gopost/conversation/zahorjan/898534

Anyone able to run the Pipe example?

**Comment by saghul** [comment]
The problem is that Pipe handles are an abstraction over Unix domain sockets but you're passing a file, so it cannot be added to epoll, and libuv aborts. If you are redirecting stdin to a file you should use the fs API, not a Pipe handle.

However, pyuv doesn't currently expose uv_guess_handle, so checking for this is not easy. I'll take care of it for next release, and hopefully provide a better example.

**Comment by saghul** [comment]
You can now use pyuv.util.guess_handle_type and use pyuv.fs.* to deal with a redirected stdin.

The program shouldn't abort, yes, but that's a libuv problem, and not quite easy to solve.
