### ISSUE TITLE
Trying to use pycurl w/ pyuv.  Request crashes if not proxied.

### ISSUE THREAD

**Issue by brizzbane** [saghul/pyuv#210]
here is example code (it's messy trying a lot of different things to try and get this working):

https://gist.github.com/brizzbane/2053dde3f4d81d7dbffa, jump down to 'test' to see, or just run.

What is odd is, I can proxy the request, and it won't crash.  Reread the docs and thought it might not be because I wasn't stopping the watcher before the socket file descriptor was closed.  pycurl maintainer added CURLOPT_CLOSEDSOCKETFUNCTION  and it still continues to crash (if I don't proxy the request).

Anyway idea whats going on?  The crash error is:

    python: src/unix/core.c:856: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.
    Aborted

Have been trying to get pycurl working on an event loop for 9+ weeks now.  Started w/tornado's curl_httpclient example, but that wasn't sufficient.  Because of the way I was using libcurl, ended up w/HIGH cpu usage.  Asked in IRC, and badger said that it was likely this issue:

"It is possible that uv_poll occasionally signals that a file descriptor is readable or writable even when it isn’t. The user should therefore always be prepared to handle EAGAIN or equivalent when it attempts to read from or write to the fd." (from https://pyuv.readthedocs.org/en/v1.x/poll.html)

If you can provide any insight would be *really* appreciated.

**Comment by moteus** [comment]
I do not use Python at all. But I am author of Lua binding for libuv and libcurl.
Did you see [this example](https://github.com/nikhilm/uvbook/blob/master/code/uvwget/main.c). I find it quite simple and easy to [port to Lua](https://github.com/moteus/lua-lluv/blob/master/examples/uvbook/uvwget/uvwget.lua). May be you can start from port it to python too.

**Comment by saghul** [comment]
The problem is the same as #54. That is, you are creating multiple `pyuv.Poll` handle objects for the same fd, which is not supported. I have not tried to integrate pycurl with pyuv, but the basic idea is to keep a dict mapping fds to Poll handles. If pycurl tells you to watch a fd for read/write, just create a Poll handle if its not there, or adapt the existing one to the new mask (you can call handle.start again no problem).

Here is an example on how to integrate pyuv with a simiilar library, c-ares: https://github.com/saghul/pycares/blob/master/examples/cares-resolver.py

**Comment by brizzbane** [comment]
Really appreciate both of your replies, they are getting me going!

Thanks.
