### ISSUE TITLE
Build of pyuv failed on Win7 64bit for python 2.7.9 64bit

### ISSUE THREAD

**Issue by gesius** [saghul/pyuv#215]
Hi guys,

on my machine the build of the extension is failing, resp. the link step. Maybe some of you had to deal with that already and can speed up my search of the causes...libuv itself as usual is building fine.
Beside that I have  2 questions:
(1) When I am using the python 2.7, I have to use the the Microsoft C/C++ Compiler V. 15.00.30729.01 for x64 from the VS 2008 (VS90). I use the Visual C++ 9.0 Compiler for Python 2.7. To ensure binary compatibillity the libuv static lib needs to be compiled also with that compiler, right? Or do I miss here something?
When my assumption is true, that the regulary libuv vcbuild.bat for windows is not following that rule either due to a higher VS version on your system (2013,2015 : in my case) or due to the missing VS MSBuild for my Visual C++ 9.0 standalone compiler. So, with that argumentation the libuv *.bat files needs to be adapted probably.
That does not mean my build failure is rooted here but maybe...I am not yet that far in my analysis.
Hope some of you may help in my questions and/or my build failure. Would really appreciate that. Thanks a lot for your efforts and engagement here....
[build-output.txt](https://github.com/saghul/pyuv/files/139258/build-output.txt)

**Comment by gesius** [comment]
At least for the Visual C++ 9.0 standalone compiler as used by many devs today the libuv.bat script is buggy:
1.  Path-to-vcvarsall.bat is incorrect despite the fact that the script assumes that the standalone compiler for 2008 will be used.
2. MSBUILD logic is not correct for VS 2008, here the VCBuild.exe is needed and not deployed with compiler package. MSBUILD is used from 2010 onwards.

**Comment by saghul** [comment]
Hi there! Before we dive any deeper, any reason why don't usre the binary wheels on PyPI?

Now, on to building. I've used VS 2008 in the past with no problem, and in order to make the wheels in AppVeyor I'm using the Windows SDK 7 as follows: https://github.com/saghul/pyuv/blob/v1.x/appveyor/run_with_env.cmd

I understand that Microsoft released that standalone compiler because of Python 2.7 though. Maybe I could make a patch for libuv adding support for it, can you point me to what path we should be loading? Thanks!

**Comment by saghul** [comment]
No follow up, closing. Builds are done with Windows SDK v7.0 in AppVeyor, I've never used that compiler myself. FWIW, you can also install the binary Wheels.
