### ISSUE TITLE
Is python 3.5 supported ?

### ISSUE THREAD

**Issue by parthibdutta** [saghul/pyuv#222]
I'm getting this error when building the pyuv 1.x version .I'm using python 3.5 .

```
C:\Users\PD\Desktop\pyuv-1.x>python setup.py build_ext --inplace
running build_ext
libuv needs to be compiled.
Building libuv...
error: No appropriate Python version found. An installation of 2.7 is required t
o build libuv. You can set the environment variable "PYTHON" to point to a custo
m installation location.
```

Is this because python 3.5 support is yet to exist ?

**Comment by saghul** [comment]
You also need to have Python 2.7 installed in order to build libuv on Windows. Absurd, I know. Blame Google for not support Python 3 in GYP.

At any rate, Python 3.5 support on Windows is broken at the moment, see #219. Once I fix that you'll be able to install a binary wheel and not worry about compilation shenanigans.
