### ISSUE TITLE
how to recv fix size data using pyuv?

### ISSUE THREAD

**Issue by cztchoice** [saghul/pyuv#223]
I have a binary protocol like 

```
struct header {
    int32_t message_type;
    int32_t message_id;
    int32_t data_size;
};
```

dataflow:
header | data | header | data |

(the protocol is from: [here](http://stackoverflow.com/questions/16082005/libuv-how-to-use-binary-protocol))

I want to first recv 12 bytes, and then recv data_size bytes.

Is there some easy way to tell pyuv to recv a fix size data? just like socket.recv(len) ?

Thanks.

**Comment by saghul** [comment]
No, that's not possible with pyuv. I've considered taking a bytearray / memoryview argument to read / recv and the reading into that, but I have not experimented with it, so don't hold your breath.

Adding a size argument would also be possible (I think) by attaching it to the handle and using in the alloc_cb. The size would need to be <= 64K, since that's the size of the slab each loop uses for reading data.

If you want to give any of these ideas a try feel free to do so and send a PR as early as possible so we can see how it evolves. Otherwise you'll need to handle this in your application, by analyzing the received data and acting accordingly.
