### ISSUE TITLE
Using with uvloop.

### ISSUE THREAD

**Issue by tomchristie** [saghul/pyuv#245]
I'm currently using uvloop in some networking code. I'm looking at using pyuv too, for file operations. Will the two end up using the same resources (thread pool?) and is there anything I should keep in mind in order to ensure they play together nicely?

Thanks & keep up the awesome work!

**Comment by saghul** [comment]
Hi Tom!

Both uvloop and pyuv use libuv, which uses an internal thread-pool for file operations. Now, if you use the two libraries in a project, each will use its own thread-pool, as they both bundle libuv. You don't need to take care of anything here.

Now, if you are using asyncio, maybe have a look at https://github.com/Tinche/aiofiles, since it does the same thing libuv does: run the given function in a thread pool (using an executor in that case).

Cheers!
