### ISSUE TITLE
 Assertion `loop->watchers[w->fd] == w' failed

### ISSUE THREAD

**Issue by geertj** [saghul/pyuv#54]
The following code will abort pyuv by triggering the assertion:

 `src/unix/core.c:651: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.`.

According to the libuv docs it is safe to close an FD after you stop() the poll handle. But even if it isn't safe, I think pyuv should not abort the program. In case of a programming error, it should raise an exception.

``` python
import os
import pyuv

def on_write(handle, events, errno):
    pass

loop = pyuv.Loop.default_loop()
r1, w1 = os.pipe()
poll1 = pyuv.Poll(loop, w1)
poll1.start(pyuv.UV_WRITABLE, on_write)
loop.run_once()  # -> pipe is writable
poll1.stop()
os.close(r1); os.close(w1)
# libuv docs tell it's safe to close the FD after stop()

r2, w2 = os.pipe()
assert w1 == w2, 'Try again'
poll2 = pyuv.Poll(loop, w2)
poll2.start(pyuv.UV_WRITABLE, on_write)
loop.run_once()
poll1.close()  # -> crash
poll2.close()
```

**Comment by brizzbane** [comment]
I'm really trying to figure out how to use libcurl (pycurl) w/python, in a nice event loop.  Have been at it for quite some time w/different implementations.

Is the issue HERE (this thread) still relevant?

My Program crashes w/:
     python: src/unix/core.c:856: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

I read in another thread that it happens during garbage collection, which might explain while It's not happening for me when going through a proxy..

Is the 'problem' OS-related/i.e. not program related.  Meaning, epoll does not support two 'watchers' for a file descriptor... and (from my understanding), libuv removed some of the 'excess' of pyev, that introduces this problem? 

I'm just starting to be able to read C and have a semi-understanding of whats going on..  if I were able to have libcurl and libuv 'looking' at the same poll hash (don't know if this is right..)--would this fix the problem below? 

     https://github.com/pycurl/pycurl/issues/324

any feedback/insight is very much appreciated.

**Comment by saghul** [comment]
Yes it is. This limitation still exists, so you have to be careful not to create 2 Poll handles for the same fd or libuv will abort.
